import type { Artwork } from '../types';

export const mockArtworks: Artwork[] = [
  {
    id: '1',
    title: 'Whisper of the Tide',
    description: 'A meditation on the liminal space between land and ocean, capturing the quiet moment where water surrenders to shore.',
    story: 'Painted during a solitary morning at the coast, this piece emerged from a desire to capture not the ocean itself, but the sensation of watching it — the rhythmic pull, the silver light dissolving into mist. It invites the viewer to pause.',
    price: 2400,
    dimensions: '80 × 100 cm',
    materials: 'Oil on linen',
    category: 'painting',
    images: [
      'https://picsum.photos/seed/tide1/900/1200',
      'https://picsum.photos/seed/tide2/900/1200',
    ],
    availability: 'available',
    framing: 'Unframed — framing available upon request',
    year: 2024,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Still Morning',
    description: 'Silence rendered in pigment. A room bathed in early light, where objects hold their breath.',
    story: 'There is a particular quality to morning light in late autumn — pale, diffused, almost hesitant. This painting attempts to hold that feeling still.',
    price: 1850,
    dimensions: '60 × 80 cm',
    materials: 'Oil on canvas',
    category: 'painting',
    images: [
      'https://picsum.photos/seed/morning1/900/1200',
      'https://picsum.photos/seed/morning2/900/1200',
    ],
    availability: 'available',
    framing: 'Natural oak float frame',
    year: 2024,
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: '3',
    title: 'Dusk Atlas',
    description: 'Layered earth tones map a journey through the hours between afternoon and night.',
    story: 'An abstract study of transition. The ochres and terracottas record the sky at the precise moment color begins to retreat.',
    price: 3200,
    dimensions: '100 × 130 cm',
    materials: 'Acrylic and oil pastel on linen',
    category: 'painting',
    images: [
      'https://picsum.photos/seed/dusk1/900/1200',
      'https://picsum.photos/seed/dusk2/900/1200',
    ],
    availability: 'sold',
    framing: 'Unframed',
    year: 2023,
    created_at: '2023-11-10T10:00:00Z',
  },
  {
    id: '4',
    title: 'Interior with Botanicals',
    description: 'Tender observation of growing things in still spaces.',
    story: 'A quiet inventory of living forms — stems in glass, leaves catching window light. A celebration of the overlooked.',
    price: 1600,
    dimensions: '50 × 70 cm',
    materials: 'Watercolor on paper',
    category: 'painting',
    images: [
      'https://picsum.photos/seed/botanical1/900/1200',
      'https://picsum.photos/seed/botanical2/900/1200',
    ],
    availability: 'available',
    framing: 'White wood frame with linen mat',
    year: 2024,
    created_at: '2024-03-05T10:00:00Z',
  },
  {
    id: '5',
    title: 'Pale Geometry',
    description: 'Form distilled to its quietest expression. Lines in tension with open space.',
    story: 'What remains when everything unnecessary is removed? This drawing explores reduction as a form of revelation.',
    price: 980,
    dimensions: '42 × 59 cm',
    materials: 'Graphite on cotton paper',
    category: 'drawing',
    images: [
      'https://picsum.photos/seed/geometry1/900/1200',
      'https://picsum.photos/seed/geometry2/900/1200',
    ],
    availability: 'available',
    framing: 'Unframed, ships in archival tube',
    year: 2024,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: '6',
    title: 'Threshold',
    description: 'A doorway, an opening, a pause before crossing. Architectural light and shadow in equilibrium.',
    story: 'Photographed in the blue hour, this archival print captures a moment of architectural stillness — the threshold as metaphor for quiet anticipation.',
    price: 750,
    dimensions: '60 × 90 cm',
    materials: 'Archival pigment print',
    category: 'photography',
    images: [
      'https://picsum.photos/seed/threshold1/900/1200',
      'https://picsum.photos/seed/threshold2/900/1200',
    ],
    availability: 'available',
    framing: 'Available framed or unframed',
    year: 2023,
    created_at: '2023-09-15T10:00:00Z',
  },
  {
    id: '7',
    title: 'Earth Study No. 3',
    description: 'A series of meditations on color found in soil, bark, and stone.',
    story: 'Drawn from samples collected during long walks in woodland, each mark is an attempt to translate tactile memory into paint.',
    price: 2100,
    dimensions: '70 × 70 cm',
    materials: 'Oil on board',
    category: 'painting',
    images: [
      'https://picsum.photos/seed/earth1/900/1200',
      'https://picsum.photos/seed/earth2/900/1200',
    ],
    availability: 'reserved',
    framing: 'Unframed',
    year: 2024,
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: '8',
    title: 'Soft Architecture',
    description: 'Buildings as emotional objects. Facades softened by memory and mist.',
    story: 'Seen from a train window, the cities blurred and became something else entirely — impressions of habitation rather than documentation of it.',
    price: 1750,
    dimensions: '65 × 85 cm',
    materials: 'Gouache on paper',
    category: 'painting',
    images: [
      'https://picsum.photos/seed/softarch1/900/1200',
      'https://picsum.photos/seed/softarch2/900/1200',
    ],
    availability: 'available',
    framing: 'Natural linen mount, simple wood frame',
    year: 2023,
    created_at: '2023-12-01T10:00:00Z',
  },
];

export const featuredArtworks = mockArtworks.filter(a => a.availability === 'available').slice(0, 3);
